# Generated by Django 4.1.2 on 2022-10-31 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolhaNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_escolha', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Data de publicação')),
                ('escolha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.escolhanew')),
            ],
        ),
        migrations.DeleteModel(
            name='Escolha',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
