# Generated by Django 4.1.2 on 2022-10-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_escolhanew_perguntanew_delete_escolha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscolhaNew',
            new_name='Escolha',
        ),
        migrations.RenameModel(
            old_name='PerguntaNew',
            new_name='Pergunta',
        ),
    ]
