# Generated by Django 4.1.2 on 2022-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_escolha_escolhanew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Data de publicação')),
            ],
        ),
        migrations.RenameModel(
            old_name='EscolhaNew',
            new_name='Choice',
        ),
        migrations.DeleteModel(
            name='PerguntaNew',
        ),
        migrations.AddField(
            model_name='question',
            name='escolha',
            field=models.ManyToManyField(blank=True, related_name='associacao', to='polls.choice'),
        ),
    ]
