# Generated by Django 4.1.2 on 2022-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='mostra_opcoes',
            field=models.BooleanField(default=True),
        ),
    ]
